env:
  browser: true
  es2021: true
extends: standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
globals:
  am4core: readable
  am4charts: readable
  am4themes_animated: readable
  am4themes_dark: readable
  am4plugins_sliceGrouper: readable
