default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://deploy@localhost') %>


development:
  platform:
    <<: *default
    database: dev_platform
   
  core:
    <<: *default
    database: dev_platform_core
    migrations_paths: db/core_migrate 

    # Use the below config instead if you want to connect to CORE for local development.
    # adapter: mysql2
    # database: core
    # encoding: utf8mb4
    # host: 127.0.0.1
    # migrations_paths: db/core_migrate
    # password: root
    # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    # port: 3307
    # protocol: tcp
    # username: root

test:
  platform:
    <<: *default
    database: test_platform
  core:
    <<: *default
    database: test_platform_core
    migrations_paths: db/core_migrate

production:
  platform:
    <<: *default
    database: production_platform    
  core:
    <<: *default
    database: production_platform_core
    migrations_paths: db/core_migrate
    url: <%= ENV.fetch('CORE_DATABASE_URL', 'mysql2://deploy@localhost') %>
